# Generated by Django 4.2 on 2023-04-17 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(max_length=20, primary_key=True, serialize=False, verbose_name='Id cliente')),
                ('nombre_cliente', models.CharField(max_length=20, verbose_name='Nombre cliente')),
                ('rut_cliente', models.CharField(max_length=20, verbose_name='Rut')),
                ('correo_cliente', models.CharField(max_length=50, verbose_name='Correo Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(max_length=20, primary_key=True, serialize=False, verbose_name='Id Compra')),
                ('compra_valor', models.CharField(max_length=20, verbose_name=' Valor compra')),
                ('id_cliente', models.CharField(max_length=20, verbose_name='Id cliente')),
                ('id_videojuego', models.CharField(max_length=50, verbose_name='Id videojuego')),
            ],
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id_juego', models.AutoField(max_length=20, primary_key=True, serialize=False, verbose_name='Id juego')),
                ('nombrejuego', models.CharField(max_length=20, verbose_name='Nombre videojuego')),
                ('tipojuego', models.CharField(max_length=20, verbose_name='Tipo de juego')),
                ('plataformajuego', models.CharField(max_length=50, verbose_name='Plataforma juego')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(max_length=20, primary_key=True, serialize=False, verbose_name='Id proveedor')),
                ('nombre_proveedor', models.CharField(max_length=20, verbose_name='Nombre proveedor')),
                ('rut_proveedor', models.CharField(max_length=20, verbose_name='Rut proveedor')),
                ('factura', models.CharField(max_length=50, verbose_name='Factura')),
            ],
        ),
        migrations.CreateModel(
            name='Reclamo',
            fields=[
                ('id_reclamo', models.AutoField(max_length=20, primary_key=True, serialize=False, verbose_name='Id Reclamo')),
                ('id_usuario', models.CharField(max_length=20, verbose_name=' Id usuario')),
                ('descripcion', models.TextField(max_length=20, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_trabajador', models.AutoField(max_length=20, primary_key=True, serialize=False, verbose_name='Id cliente')),
                ('nombre_trabajador', models.CharField(max_length=20, verbose_name='Nombre Trabajador')),
                ('rut_trabajador', models.CharField(max_length=20, verbose_name='Rut')),
                ('correo_trabajador', models.CharField(max_length=50, verbose_name='Correo trabajador')),
            ],
        ),
    ]
